##################################################
### all postgres ###
- hosts: nfs_server
  become: true
  tasks:
    - name: install packages epel-release and net-tools
      yum: 
        name:
          - epel-release
          - net-tools
          - sysstat
    - name: Disable selinux
      selinux: 
        state: disabled
      notify:
        - restart system
    - name: disable firewalld
      systemd: 
        name: firewalld
        enabled: no
  handlers:
    - name: restart system
      reboot: 
        reboot_timeout: 300


- hosts: nfs_server
  become: true
  roles:
    - nfs

- hosts: nfs_client
  become: true
  roles:
    - nfs_client

- hosts: nfs_server
  become: true
  tasks:
    - name: install packages htop
      yum: 
        name:
          - htop
          - vim
          - atop

