---

#- hosts: PostgreSQL
#  tasks:
#    - lineinfile:
#        path: /etc/sudoers
#        state: present
#        regexp: '^# %wheel'
#        line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
#        validate: 'visudo -cf %s'

##################################################
### all postgres ###
- hosts: PostgreSQL
  become: true
  tasks:
    - name: install packages epel-release and net-tools
      yum: 
        name:
          - epel-release
          - net-tools
          - sysstat
    - name: Disable selinux
      selinux: 
        state: disabled
      notify:
        - restart system
    - name: disable firewalld
      systemd: 
        name: firewalld
        enabled: no
  handlers:
    - name: restart system
      reboot: 
        reboot_timeout: 300


- hosts: PostgreSQL
  become: true
  roles:
    - postgres1c

- hosts: PostgreSQL
  become: true
  tasks:
    - name: install packages htop
      yum: 
        name:
          - htop
          - vim
          - atop
