---

- name: Enable port for http in firewalld 
  firewalld:
    zone: public
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: NGINX | Install EPEL Repo package from standard repo
  yum:
    name: epel-release
    state: present
  tags:
    - epel-package
    - packages
  when: ansible_os_family == "RedHat"

- name: NGINX | Install nginx package from epel repo RedHat
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages
  when: ansible_os_family == "RedHat"
  
- name: NGINX | Install nginx package Ubuntu
  apt:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages
  when: ansible_os_family == "Debian"
  
- name: NGINX | Create NGINX config file from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-configuration
