---

- name: Enable port for http in firewalld 
  firewalld:
    zone: public
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: NGINX | Install EPEL Repo package from standard repo
  yum:
    name: epel-release
    state: present
  tags:
    - epel-package
    - packages
  when: ansible_os_family == "RedHat"

- name: NGINX | Install nginx package from epel repo RedHat
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages
  when: ansible_os_family == "RedHat"
  
- name: NGINX | Install nginx package Ubuntu
  apt:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages
  when: ansible_os_family == "Debian"
  
- name: NGINX | Create NGINX config file from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-configuration


- name: install for developer lib
  yum:
    name:
    - bison
    - byacc
    - cscope
    - ctags
    - cvs
    - diffstat
    - doxygen
    - flex
    - gcc
    - gcc-c++
    - gcc-gfortran
    - gettext
    - git
    - indent
    - intltool
    - libtool
    - patch
    - patchutils
    - rcs
    - redhat-rpm-config
    - rpm-build
    - subversion
    - swig
    - systemtap

- name: Download to specified path
  get_url:
    url: http://nginx.org/download/nginx-1.12.2.tar.gz
         http://nginx.org/download/nginx-1.12.2.tar.gz
    dest: /usr/share/nginx
    #nginx-1.12.2.tar.gz

#- name: ansible create directory outs
#  file: path=/usr/share/nginx/nginx-1.12.2 state=directory owner=root group=root

- name: Unarchive a file that
  unarchive:
    src: /usr/share/nginx/nginx-1.12.2.tar.gz
    dest: /usr/share/nginx/
    owner: root
    group: root
    remote_src: yes

- name: Create new module
  shell: /usr/share/nginx/nginx-1.12.2/configure --with-pcre=ngx_http_rewrite_module
#--with-pcre=ngx_http_headers_module  --without-http_gzip_module

make modules
sudo make install
