---
# handlers file for Quagga
- name: Restart zebra service
  systemd:
    name: zebra
    state: restarted
    enabled: yes
- name: Restart ospfd service
  systemd:
    name: ospfd
    state: restarted
    enabled: yes
- name: restart system
  reboot: 
      reboot_timeout: 300