---
# handlers file for nfs_client

- name: restart rpcbind.service
  systemd: 
    name: rpcbind.service
    enabled: yes
    state: restarted

- name: restart nfs-server.service
  systemd: 
    name: nfs-server.service
    enabled: yes
    state: restarted