---
# tasks file for nfs

- name: install nfs servers
  yum:
    name: nfs-utils
    state: latest
  notify:
    - restart rpcbind.service
    - restart nfs-server.service

# rpcinfo -p localhost #Проверяем для каких версий NFS способен принимать подключения наш NFS-сервер

##############################################
### nassrv10
- name: create directory for backup
  file: path=/pg_backup state=directory mode=0777
  when: ansible_facts['hostname'] == "nassrv10"

- name: Mount up device for backup
  mount: path=/pg_backup src=/dev/pg_backup/data fstype=ext4 state=mounted
  when: ansible_facts['hostname'] == "nassrv10"

- name: create directory for pgsrv10
  file: path=/pg_backup/pgsrv10/{{ item }}/data state=directory mode=0777
  loop:
    - dev
    - outs
    - audit
  when: ansible_facts['hostname'] == "nassrv10"

- name: create directory for pgsrv10
  file: path=/pg_backup/pgsrv10/{{ item }}/xlog state=directory mode=0777
  loop:
    - dev
    - outs
    - audit
  when: ansible_facts['hostname'] == "nassrv10"

- name: create directory for pg_cluster_audit
  file: path=/pg_cluster_audit state=directory
  when: ansible_facts['hostname'] == "nassrv10"

- name: Mount up device for pg_cluster_audit
  mount: path=/pg_cluster_audit src=/dev/pg_cluster/audit fstype=ext4 state=mounted
  when: ansible_facts['hostname'] == "nassrv10"


- name: copy config nfs shear
  copy: src=nassrv10-exports dest=/etc/exports mode=0644
  when: ansible_facts['hostname'] == "nassrv10"
  
- name: reload config nfs
  shell: exportfs -r

# firewall-cmd --permanent --zone=public --add-service=nfs
# firewall-cmd --permanent --zone=public --add-service=mountd
# firewall-cmd --permanent --zone=public --add-service=rpc-bind
# firewall-cmd --reload
# 10.6.9.23 /24