---
# tasks file for Quagga

- name: Kernel is allowed to routing
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: install Quagga
  yum:
    name: quagga
    state: latest

- name: copy info daemons
  copy: 
    src: daemons
    dest: /etc/quagga/daemons group=quagga owner=quagga
  notify:
    - Restart zebra service
    - Restart ospfd service
#- name: Copy zebra config
#  template: src=quagga.conf.j2 dest=/etc/quagga/zebra.conf
#  notify: Reload zebra service

- name: Copy quagga config
  template: 
    src: ospfd.conf.j2
    dest: /etc/quagga/ospfd.conf group=quagga owner=quagga
  notify: 
    - Restart zebra service
    - Restart ospfd service
