# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
    :box_name => "centos/7",
    :ssh_port => 33111,
    #:web_port => 8082,
    :ip_addr => '192.168.100.111'
  },
  :slave => {
    :box_name => "centos/7",
    :ssh_port => 33112,
    #:web_port => 8082,
    :ip_addr => '192.168.100.112'
  },
  :proxy => {
    :box_name => "centos/7",
    :ssh_port => 33113,
    #:web_port => 8082,
    :ip_addr => '192.168.100.113'
  },
  :nginx1 => {
    :box_name => "centos/7",
    :ssh_port => 33201,
    :web_port => 8081,
    :ip_addr => '192.168.100.201'
  },
  :nginx2 => {
    :box_name => "centos/7",
    :ssh_port => 33202,
    :web_port => 8082,
    :ip_addr => '192.168.100.202'
  },
  :nginx3 => {
    :box_name => "centos/7",
    :ssh_port => 33203,
    :web_port => 8083,
    :ip_addr => '192.168.100.203'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.network :forwarded_port, guest: 22, host: boxconfig[:ssh_port], id: "ssh", auto_correct: true
          if boxconfig.key?(:web_port)
            box.vm.network :forwarded_port, guest: 80, host: boxconfig[:web_port], id: "http", auto_correct: true
          end
          
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL
          #case boxname.to_s
          #when "nginx2"
          #  box.vm.provision "shell", inline: <<-SHELL
          #    sudo apt-get -y install python-minimal
          #  SHELL
          #end 

          if boxname.to_s == "nginx3"
            box.vm.provision "ansible" do |ansible|
              #ansible.verbose = "v"
              ansible.playbook = "provisioning/pb_general.yml"
              ansible.become = "true"
              ansible.inventory_path = "staging/hosts"
              #ansible.limit = "all"
              ansible.limit = "nginx1 nginx2 nginx3"
            end
          end
      end
  end
end
