---
# tasks file for iptables

# centralRouter
- name: iptables -I FORWARD -j ACCEPT
  iptables:
    table: filter
    chain: FORWARD
    jump: ACCEPT
    action: insert
    rule_num: 1
    comment: accept trafic route iptables -I FORWARD -j ACCEPT
  become: yes
  when: ansible_facts['hostname'] == "centralRouter"

# inetRouter2    
- name: Forward port 8080 to 80
  iptables:
    table: nat
    chain: PREROUTING
    #in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: '80'
    destination: '192.168.0.2'
    #centralServer
    jump: DNAT
    to_destination: '192.168.0.2:8080'
    #to_ports: '8080'
    comment: Redirect web traffic to port 8080 in centralServer
  become: yes
  when: ansible_facts['hostname'] == "inetRouter2"