# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :RaidDisk02ChengeSystem => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	      :disks => {
		        :sata1 => {
			          :dfile => 'f:/diskVirtualBox/linux/sata1.vdi',
			          :size => 20000,
			          :port => 1
		        },
		        :sata2 => {
                :dfile => 'f:/diskVirtualBox/linux/sata2.vdi',
                :size => 20000, 
			          :port => 2
		        },
            :sata3 => {
                :dfile => 'f:/diskVirtualBox/linux/sata3.vdi',
                :size => 20000,
                :port => 3
            },
            :sata4 => {
                :dfile => 'f:/diskVirtualBox/linux/sata4.vdi',
                :size => 20000, 
                :port => 4
            }
        }
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.box_check_update = false
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
                vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
                needsController = false
                boxconfig[:disks].each do |dname, dconf|
                    unless File.exist?(dconf[:dfile])
                        vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                        needsController =  true
                    end
                end
                if needsController == true
                    vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                    boxconfig[:disks].each do |dname, dconf|
                        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                    end
                end
            end
        
            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                yum install -y mdadm smartmontools hdparm gdisk vim
                sudo mkdir -p /home/vagrant/bin
                sudo cp /vagrant/init_raid.sh /home/vagrant/bin/init_raid.sh
                sudo chmod guo+x /home/vagrant/bin/init_raid.sh
                sudo cat /home/vagrant/bin/init_raid.sh
                sudo /home/vagrant/bin/init_raid.sh
            SHELL
    end
  end
end