---
# tasks file for postgres1c

#####################################################
###  iscisi init by NETAP mazars ###
- name: install packages iscsi-initiator-utils
  yum: 
    name:
      - iscsi-initiator-utils
      - device-mapper-multipath
- name: copy information about target
  copy: src=pgsrv10-initiatorname.iscsi dest=/etc/iscsi/initiatorname.iscsi mode=0644
  notify:
    - restart iscsid.service
    - restart multipathd.service

# нужен для работы netap, отображается два диска вместо одного
- name: Add the dm-multipath module
  modprobe:
    name: dm-multipath
    state: present

- name: Copy config files for multipath
  copy: src=pgsrv10-multipath.conf dest=/etc/multipath.conf
  notify:
    - restart multipathd.service
  #- name: discavery target
  #  shell: iscsiadm -m discovery -t sendtargets -p 10.6.9.12 # discavery netap mazars
  #  shell: iscsiadm -m discovery -t sendtargets -p 10.6.9.12 # discavery netap mazars
  #  shell: iscsiadm -m node # show node
  #  shell: iscsiadm -m node -l -T iqn.1992-08.com.netapp:sn.142247380 # log in netap
   #  shell: iscsiadm -m session -P3 # show session connect
  #  shell: iscsiadm -m node -r -T iqn.1992-08.com.netapp:sn.142247380 # log out netap
  # firewall-cmd --permanent --zone=public --add-port=3260/tcp

#####################################################
###  general settings  ###
- name: install locale ru_RU.UTF-8
  shell: localedef  -i ru_RU -f UTF-8 ru_RU.UTF-8

- name: ansible create directory distrib
  file:
    path: /distrib
    state: directory

- name: copy distrib
  copy: 
    src: "{{ item }}" 
    dest: "/distrib/{{ item }}" 
    mode: 0770
  loop:
    - postgresql10-1c-10.5-24.el7.x86_64.rpm
    - postgresql10-1c-contrib-10.5-24.el7.x86_64.rpm
    - postgresql10-1c-libs-10.5-24.el7.x86_64.rpm
    - postgresql10-1c-server-10.5-24.el7.x86_64.rpm
- name: install packages
  yum: 
    name: 
    - openssl
    - readline
    - krb5-libs
  #  - libicu50
    state: latest 
  
- name: install postgres1c from a local file
  yum:
    name: 
    - /distrib/postgresql10-1c-libs-10.5-24.el7.x86_64.rpm
    - /distrib/postgresql10-1c-10.5-24.el7.x86_64.rpm
    - /distrib/postgresql10-1c-server-10.5-24.el7.x86_64.rpm
    - /distrib/postgresql10-1c-contrib-10.5-24.el7.x86_64.rpm
    state: present

########################################################3
#### Setup pgsrv10 ####
### demon for postgres ###
- name: copy files for demone pgsrv
  copy: 
    src: "{{ item }}" 
    dest: "/usr/lib/systemd/system/{{ item }}" 
    mode: 0644
  loop:
    - postgresql-10-audit.service
    - postgresql-10-dev.service
  when: ansible_facts['hostname'] == "pgsrv10"
##############################################################
### dev cluster ###
- name: ansible create directory dev_cluster
  file: path=/mnt/pg_dev_cluster state=directory owner=postgres group=postgres
  when: ansible_facts['hostname'] == "pgsrv10"

- name: Mount up device dev server
  mount: path=/var/lib/pgsql/10/dev_cluster src=/dev/pg_cluster/dev fstype=ext4 state=mounted
  when: ansible_facts['hostname'] == "pgsrv10"

- name: Change file ownership, group and permissions
  file: path=/var/lib/pgsql/10/dev_cluster state=directory owner=postgres group=postgres mode=0700

- name: Ansible delete file lost+found
  file:
    path: /var/lib/pgsql/10/dev_cluster/lost+found
    state: absent

- name: init claster postgres1c dev
  shell: /usr/pgsql-10/bin/initdb --locale=ru_RU.UTF-8 -D /var/lib/pgsql/10/dev_cluster
  become_user: postgres
  ignore_errors: yes
  when: ansible_facts['hostname'] == "pgsrv10"

- name: copy config files postgres1c dev pgsrv10
  copy: src=pgsrv10-postgresql-dev.conf dest=/var/lib/pgsql/10/dev_cluster/postgresql.conf
  notify: 
    - Restart postgres1c dev
  when: ansible_facts['hostname'] == "pgsrv10"

- name: State postgres1c dev
  systemd:
    name: postgresql-10-dev.service
    state: started
  when: ansible_facts['hostname'] == "pgsrv10"
##############################################################
### audit cluster ###

- name: ansible create directory audit_cluster
  file: path=/var/lib/pgsql/10/audit_cluster state=directory owner=postgres group=postgres
  when: ansible_facts['hostname'] == "pgsrv10"

- name: Mount up device for audit_cluster
  mount: path=/var/lib/pgsql/10/audit_cluster src=nassrv10:/pg_cluster_audit fstype=nfs state=mounted
  when: ansible_facts['hostname'] == "pgsrv10"

- name: Ansible delete file lost+found
  file:
    path: /var/lib/pgsql/10/audit_cluster/lost+found
    state: absent

- name: init claster postgres1c audit
  shell: /usr/pgsql-10/bin/initdb --locale=ru_RU.UTF-8 -D /var/lib/pgsql/10/audit_cluster
  become_user: postgres
  ignore_errors: yes
  when: ansible_facts['hostname'] == "pgsrv10"

- name: copy config files postgres1c audit pgsrv10
  copy: src=pgsrv10-postgresql-audit.conf dest=/var/lib/pgsql/10/audit_cluster/postgresql.conf
  notify: 
    - Restart postgres1c audit
  when: ansible_facts['hostname'] == "pgsrv10"

- name: State postgres1c audit
  systemd:
    name: postgresql-10-audit.service
    state: started
  when: ansible_facts['hostname'] == "pgsrv10"
##############################################################
### outs cluster ###

- name: ansible create directory outs
  file: path=/var/lib/pgsql/10/data state=directory owner=postgres group=postgres
  when: ansible_facts['hostname'] == "pgsrv10"

- name: Mount up device outs server
  mount: path=/var/lib/pgsql/10/data src=/dev/pg_cluster2/outs fstype=ext4 state=mounted
  when: ansible_facts['hostname'] == "pgsrv10"


- name: Ansible delete file lost+found
  file:
    path: /var/lib/pgsql/10/data/lost+found
    state: absent

- name: init claster postgres1c outs
  shell: /usr/pgsql-10/bin/initdb --locale=ru_RU.UTF-8 -D /var/lib/pgsql/10/data
  become_user: postgres
  ignore_errors: yes
  when: ansible_facts['hostname'] == "pgsrv10"

- name: copy config files postgres1c outs pgsrv10
  copy: src=pgsrv10-postgresql.conf dest=/var/lib/pgsql/10/data/postgresql.conf
  notify: 
    - Restart postgres1c outs
  when: ansible_facts['hostname'] == "pgsrv10"

- name: State postgres1c outs
  systemd:
    name: postgresql-10.service
    state: started
#############################################
### other activiti ###






#############################################
### not use but perhab ###
#- name: copy config files postgres1c pgsrv10 pg_hba
#  copy: src=pgsrv10-pg_hba.conf dest=/var/lib/pgsql/10/data/pg_hba.conf
#  notify: 
#    - Restart postgres1c outs
#  when: ansible_facts['hostname'] == "pgsrv10"
