---


#Dynamic routing run router server (OSPF Quagga) 
- hosts: servers
  become: true
  tasks:
    - name: Set gateway
      command: echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      notify:
        - restart network
    - name: Set DEFROUTE = no
      command: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
      notify:
        - restart network
  handlers:
    - name:  restart network
      systemd:
        name: network
        state: restarted

#inetRoute
- hosts: all 
  become: true
  #vars: 
  #  inetRouter_ip: '192.168.255.5/30'
  #  inetRouter_gw: '192.168.0.1'
  
  tasks:
  - name: install 
    yum: 
      name:
      - python-gobject
      - NetworkManager-glib
      - epel-release

  #- name: set eth
  #  nmcli:
  #    conn_name: eth1 
  #    ifname: eth1
  #    type: ethernet
  #    ip4: 192.168.255.15/24
  #    gw4: "192.168.255.1"
  #    state: present
   

- hosts: routers
  become: true
  roles:
    - quagga
