---

#Dynamic routing run router server (OSPF Quagga) 
- hosts: servers
  become: true
  tasks:
    - name: Set gateway
      command: echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      notify:
        - restart network
    - name: Set DEFROUTE = no
      command: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
      notify:
        - restart network
  handlers:
    - name:  restart network
      systemd:
        name: network
        state: restarted

inetRouter_ip = '192.168.255.1'
#netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
- hosts: inetRouter
  # nmcli_team:
  conn_name: inetRouter
    ip4: '{{ inetRouter_ip }}'
    gw4: '{{ inetRouter_gw }}'
  conn_name: external
    ip4: '{{ external_ip }}'
    gw4: '{{ external_gw }}'
  conn_name: storage
    ip4: '{{ storage_ip }}'
    gw4: '{{ storage_gw }}'


- hosts: routers
  become: true
  roles:
    - quagga
