---
# tasks file for nginx
- name: Enable port for http in firewalld 
  firewalld:
    zone: public
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: NGINX | Install nginx package from epel repo RedHat
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx

- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
