---
# tasks file for os
- name: enable firewalld
  systemd: 
    name: firewalld
    state: started
    enabled: yes

- name: Enable port for zabbix-agent in firewalld 
  firewalld:
    zone: public
    service: zabbix-agent
    permanent: yes
    immediate: yes
    state: enabled

- name: install packages epel-release
  yum: 
    name:
    - epel-release
    - https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm

- name: install packages other
  yum: 
    name:
    - net-tools
    - sysstat
    - htop
    - vim
    - atop
    - zabbix-agent
    - telnet
    - chrony

- name: enable zabbix-agent
  systemd: 
    name: zabbix-agent
    state: started
    enabled: yes

- name: Set timezone to Asia/Tokyo
  timezone:
    name: Europe/Moscow

- name: enable chrony
  systemd: 
    name: chronyd
    state: started
    enabled: yes