---
# Runs only on host1
- hosts: host1
  become: true
  gather_facts: false
  tasks:

  - name: Install packages only on host1
    yum:
      name:
        - epel-release
        - telnet
        - vim 
        - htop
      state: latest

# Runs only on host2      
- hosts: host2
  become: true
  gather_facts: false
  tasks:

  - name: Install packages only on host1
    yum:
      name:
        - bind-utils
        - epel-release
        - net-tools
      state: latest
       


